name: Build and release packages

on:
  pull_request:
  workflow_dispatch:

env:
  ZAP_TEST_TIMEOUT: 3600000
  ZAP_TEMPSTATE: 1

jobs:
  # To test locally via https://github.com/nektos/act
  #   act -j matter-sdk-codegen
  matter-sdk-codegen:
    name: Test matter sdk codegen changes
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]

    # CHIP container required because clang-format version needs to match
    container:
      image: connectedhomeip/chip-build:0.6.11

    steps:
      - uses: actions/checkout@v3

      # Checkout without actions/checkout@v3 since that one uses a repository specific token
      - name: Checkout Matter SDK
        run: |
          git clone --depth 1 https://github.com/project-chip/connectedhomeip.git chip_repo

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: ./src-script/install-packages-ubuntu
      - run: apt-get install -y --fix-missing xvfb git
      - run: npm ci
      - run: npm run version-stamp
      - run: npm rebuild canvas --update-binary
      - run: npm rebuild libxmljs --update-binary
      - run: npm run build-spa

      - name: Generate all
        run: |
          cd chip_repo
          ZAP_DEVELOPMENT_PATH=.. scripts/tools/zap_regen_all.py

      - name: Ensure git works in the chip repository checkout
        run: git config --global --add safe.directory `pwd`/chip_repo

      - name: Check for uncommited changes
        run: |
          cd chip_repo
          git add .
          # Show the full diff
          git diff-index -p HEAD --
          # Also show just the files that are different, to make it easy
          # to tell at a glance what might be going on.  And throw in
          # --exit-code to make this job fail if there is a difference.
          git diff-index --exit-code HEAD --

